spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/persondict
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog.xml
personDict:
  defaultSize: 5